import Aos from 'aos/src/js/aos.js';
import '@/js/loader.js';
Aos.init();
import '@/js/iziToast.js';
import '@/js/slider.js';
import '@/js/header.js';
import '@/js/hero.js';
import '@/js/about-me.js';
import '@/js/skills-list.js';
import '@/js/benefits.js';
import '@/js/projects.js';
import '@/js/faq.js';
import '@/js/covers.js';
import '@/js/reviews.js';
import '@/js/work-together.js';
import '@/js/modal.js';
import '@/js/theme-swither.js';